name: tdmpc
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch-gpu=1.9.1
  - torchvision
  - cudatoolkit=11.0.3
  - pillow
  - numpy=1.23.5
  - setuptools=65.5.0
  - wheel<0.40.0
  - pandas
  - omegaconf
  - termcolor
  - gym==0.21.0
  - wandb
  - imageio
  - moviepy
  - pip
  - pip:
    - dm-control==0.0.403778684
