name: tdmpc
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.1
  - torchvision
  - cudatoolkit=11.0.3
  - pillow
  - pip
  - pip:
    - termcolor
    - omegaconf
    - gym==0.21.0
    - dm-control==0.0.403778684
    - pandas
    - wandb
    - moviepy
    - imageio
    - numpy=1.23.5